const Koop = require('koop')
const koop = new Koop()
const vectorTiles = require('../')
const craigslist = require('koop-provider-craigslist')
const googlesheets = require('@koopjs/provider-google-sheets')
koop.register(vectorTiles)
koop.register(craigslist)
koop.register(googlesheets)
koop.server.listen(8085)
